#!/bin/sh /etc/rc.common

START=99
STOP=10
USE_PROCD=1

PROG=/usr/bin/clawrt

start_service() {
	config_load clawrt

	local enabled
	config_get_bool enabled main enabled 0

	[ "$enabled" -eq 1 ] || return 0

	procd_open_instance clawrt
	procd_set_param command "$PROG" -config /etc/config/clawrt
	procd_set_param respawn 3600 5 0
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

reload_service() {
	stop
	start
}
